### ISSUE TITLE
Actividad_7

### ISSUE THREAD

**Issue by 22620188Oliverio** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equpio-lor-xd#1]
https://github.com/SistemasTecTlaxiaco/TokenEats/wiki

**Comment by Reyesjessica** [comment]
26, la estructura del documento está incompleta ya que le falta la lista de figuras, lista de tablas y la descripción del sistema actual, de la misma forma falto mencionar los números de requisitos funcionales en los diagramas de caso de uso.

**Comment by josealfredo79** [comment]
bien comentado los puntos que hacen falta...favor de mejorar

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
